### ISSUE TITLE
Desarrollo_login

### ISSUE THREAD

**Issue by AlmaDianaSotoCervantes** [AlmaDianaSotoCervantes/soto_cervantes_parcial_2#1]
diseñar login de acceso

**Comment by AlmaDianaSotoCervantes** [comment]
credenciales de login de acceso @ingreyeslara 
Usuario: ingreyeslara
Contraseña: Utd_2024

link: https://almadianasotocervantes.projectsutd.online/Soto_Cervantes_parcial_2/

**Comment by ingreyeslara** [comment]
CORRECTO, LIBERADO!!!!!!
